version: '3'
services:
  frontend:
    image: node:16-alpine
    container_name: anlix_test_front
    working_dir: /app
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    command: sh
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - REACT_APP_HOST=backend
    depends_on:
      - backend
  backend:
    image: node:16-alpine
    container_name: anlix_test_back
    working_dir: /app
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true
    command: sh
    ports:
      - 3001:3001
    restart: on-failure