type Pulmonary {
    data: String!
    exame: [ExamePulmonary!]!
}

type ExamePulmonary {
    CPF: String!
    EPOC: String!
    ind_pulm: String!
    paciente: [Patient!]
}

type Query {
    getExamsPulmonary: [Pulmonary!]!
    getExamPulmonaryByCpf(CPF: String!): [Pulmonary!]! 
    getExamPulmonaryByDateAndCpf(data: String!, CPF: String!): [Pulmonary!]!
    getExamPulmonaryByDate(data: String!): [Pulmonary!]!
    getExamPulmonaryWithInterval(dataInicial: String!, dataFinal: String!, CPF: String!): [Pulmonary!]!
    getExamPulmonaryWithIntervalValue(valorInicial: String!, valorFinal: String!, CPF: String!): [Pulmonary!]!
}